name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/*  # This includes all files in the repository in the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

